### ISSUE TITLE
How to create an AKS StatefulSet with Azure Storage Key

### ISSUE THREAD

**Issue by JulioFor** [andyzhangx/demo#10]
I know there is posible to use Azure Files from AKS if you give permissions over the storage account to your sp or managed id.
But is it possible to create a StatefulSet if you are not allowed to give such access and only have storage key.

With normal deploys is possible since you only need to have the secret and to use secretName or even include shareName in order to have always the same name.
But when it comes to StatefulSet, wich uses volumeClaimTemplates,  It seems imposible, unless yo have permissions over the storage as mentioned before.

**Comment by andyzhangx** [comment]
@JulioFor yes, that's possible, just follow this example, it has a statefulset example with account key: https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/deploy/example/e2e_usage.md#option2-bring-your-own-storage-account-only-for-smb-protocol
