### ISSUE TITLE
Doc issue about image pull error?

### ISSUE THREAD

**Issue by zhongyi-zhang** [andyzhangx/demo#7]
https://github.com/andyzhangx/demo/blob/master/issues/acr-issues.md#2-image-pull-error-from-acr-anonymous-repository said that image pull error for public ACR was fixed in v1.13.4. That looks not right -- https://github.com/kubernetes/kubernetes/blob/v1.13.4/pkg/credentialprovider/azure/azure_credentials.go doesn't include the fix. Instead, it is v1.13.5 including the fix: https://github.com/kubernetes/kubernetes/blob/v1.13.5/pkg/credentialprovider/azure/azure_credentials.go.

**Comment by andyzhangx** [comment]
correct, I have changed the fixed version from `1.13.4` to `1.13.5`
